name = "M3DC1"
uuid = "ebf85914-40aa-4f90-a512-07886c23a495"
authors = ["Brendan C. Lyons"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
